### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by aronovgj** [C-Duv/chocolatey-pdfsam#3]
New releases have been out for quite some time. Will there be updates?

I sent a maintainer mail but I'm not sure if it arrived, as I did not get a copy.

**Comment by C-Duv** [comment]
I don't recall of such e-mail.
I'll start to catch up with upstream updates today.

**Comment by aronovgj** [comment]
Please note that the public feed now requires checksums. Also, the dependency should not be on `javaruntime` but on `jre8`.

**Comment by C-Duv** [comment]
Thanks, I had forgotten about checksums ;)
Why do you suggest `jre8` when `javaruntime` is Java v8?

**Comment by aronovgj** [comment]
Never mind. thought `javaruntime` was deprecated but it is a virtual package.

**Comment by C-Duv** [comment]
Installer for version 3.2.2 has been submitted to Chocolatey.org: awaiting approval.

**Comment by aronovgj** [comment]
Did not quite get why you pushed the earlier releases too, don't think anyone would care. Anyway, new versions are approved. 

Please consider making it an automatic package:
https://chocolatey.org/docs/automatic-packages

Also: thanks
